name: daily
favicon: null
layout_spectrum: 0.73034
typography_spectrum: 0.25171
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d0d0d0'
    - '#e94d41'
    - '#54b5d5'
    - '#60605e'
    - '#e9928c'
  brandStrength: 0
  lightness: 1
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
