name: daily
favicon: null
layout_spectrum: 0.24443
typography_spectrum: 0.65212
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#514046'
    - '#0b0100'
    - '#f04f3b'
    - '#fefdfe'
    - '#e0ccdb'
  brandStrength: 1
  lightness: 1
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
