name: daily
favicon: null
layout_spectrum: 1
typography_spectrum: 0.25171
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff0200'
    - '#222222'
    - '#202020'
    - '#202020'
    - '#202020'
  brandStrength: 0
  lightness: 1
  saturation: 0.4375
  rhythmicContrast: 0
purpose: []
