name: daily
favicon: null
layout_spectrum: 0.27549313730560243
typography_spectrum: 0.975500404369086
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.3963191327638924
  lightness: 0.007776801474392414
  saturation: 0.33482325403019786
  rhythmicContrast: 0.07777710095979273
purpose: []
